# Generated by Django 5.1.4 on 2024-12-15 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='persona',
            name='genero_persona',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=50)),
                ('id_gobernador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.region')),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=50)),
                ('id_alcalde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('id_vivienda', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_vivienda', models.CharField(max_length=100)),
                ('estrato_vivienda', models.IntegerField()),
                ('id_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.municipio')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaResideVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.persona')),
                ('id_vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=50)),
                ('especie_mascota', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(max_length=50)),
                ('id_vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vivienda')),
            ],
        ),
    ]
