# Generated by Django 5.1.4 on 2024-12-16 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_region_alter_persona_genero_persona_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id_gobernador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='id_alcalde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.persona'),
        ),
    ]
